DROP database bloodbank;
Create database bloodbank;

\c bloodbank


CREATE TABLE	HOSPITAL
( H_ID VARCHAR(10) NOT NULL,
  H_Name CHAR(50) NOT NULL,
  H_Phone DECIMAL(10,0) NOT NULL,
  H_Address VARCHAR(50) NOT NULL,
  PRIMARY KEY (H_ID) );

CREATE TABLE	PATIENT
( P_ID VARCHAR(20) NOT NULL,
  P_Name CHAR(30) NOT NULL,
  P_Gender CHAR(2) NOT NULL,
  P_Phone DECIMAL(10,0),
  P_Address VARCHAR(50) NOT NULL,
  P_Type CHAR(5) NOT NULL,
  H_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (P_ID),
  FOREIGN KEY (H_ID) REFERENCES HOSPITAL (H_ID) );

CREATE TABLE VOLUNTEER_AGENCY
( V_ID VARCHAR(10) NOT NULL,
  V_date DATE,
  V_place varchar(50),
  PRIMARY KEY (V_ID));



CREATE TABLE VOLUNTEER_NGO
( V_ID VARCHAR(10) NOT NULL,
  N_ID VARCHAR(10) NOT NULL,
  N_NAME VARCHAR(50),
  PRIMARY KEY (N_ID),
  FOREIGN KEY (V_ID) REFERENCES VOLUNTEER_AGENCY (V_ID) );

CREATE TABLE VOLUNTEER_IND
( V_ID VARCHAR(10) NOT NULL,
  I_ID VARCHAR(10) NOT NULL,
  I_NAME VARCHAR(50),
  PRIMARY KEY (I_ID),
  FOREIGN KEY (V_ID) REFERENCES VOLUNTEER_AGENCY (V_ID));


CREATE TABLE	DONOR
( D_ID VARCHAR(10) NOT NULL,
  Fname VARCHAR(30) NOT NULL,
  Mname VARCHAR(25),
  Lname VARCHAR(30) NOT NULL,
  V_ID VARCHAR(10) NOT NULL,
  DOB DATE,
  D_Phone DECIMAL(10,0) NOT NULL,
  D_Gender CHAR(1),
  D_Type CHAR(5),
  STREET VARCHAR(50) NOT NULL,
  LOCALITY VARCHAR(50) NOT NULL,
  CITY VARCHAR(50) NOT NULL,
  PRIMARY KEY (D_ID),
  FOREIGN KEY (V_ID) REFERENCES VOLUNTEER_AGENCY (V_ID));
  
		
CREATE TABLE 	MED_CONDITION
( C_ID VARCHAR NOT NULL,
  D_ID VARCHAR(20) NOT NULL,
  CONDITION VARCHAR(50),
  MEDICATION VARCHAR(50),
  ADD_DETAILS VARCHAR(50),
  PRIMARY KEY (C_ID),
  FOREIGN KEY (D_ID) REFERENCES DONOR(D_ID) );
  
CREATE TABLE	BLOOD_BANK
( Branch_ID VARCHAR(10) NOT NULL,
  Branch_Name CHAR(50),
  Order_no INT ,
  Issues VARCHAR,
  Emp_ID VARCHAR(50),
  PRIMARY KEY (Branch_ID) );

CREATE TABLE	MANAGER
( Emp_ID VARCHAR(10) NOT NULL,
  BRANCH_ID VARCHAR(10) NOT NULL,
  E_ADDRESS VARCHAR(50) NOT NULL,
  E_Phone DECIMAL(10,0) NOT NULL,
  E_Email VARCHAR(30) NOT NULL,
  E_Name CHAR(30) NOT NULL,
  PRIMARY KEY (Emp_ID),
  FOREIGN KEY (BRANCH_ID) REFERENCES BLOOD_BANK (BRANCH_ID) );


CREATE TABLE	BLOOD
( B_ID VARCHAR(10) NOT NULL,
  D_ID VARCHAR(10) NOT NULL,
  Date_Donate DATE,
  Type_blood CHAR(5) NOT NULL,
  BRANCH_ID VARCHAR(10),
  PRIMARY KEY (B_ID),
  FOREIGN KEY (D_ID) REFERENCES DONOR (D_ID),
  FOREIGN KEY (BRANCH_ID) REFERENCES BLOOD_BANK (BRANCH_ID)  );


CREATE TABLE STOCK
( Branch_ID VARCHAR(20) NOT NULL, 
  BLOOD_Type CHAR(20),
  count INT NOT NULL,
  FOREIGN KEY (Branch_ID) REFERENCES BLOOD_BANK (Branch_ID) );
  

CREATE TABLE ORDER_BLOOD
( ORDER_ID INT NOT NULL,
  H_ID VARCHAR(10) NOT NULL,
  BLOOD_TYPE CHAR(5) NOT NULL,
  UNITS INT NOT NULL,
  BRANCH_ID VARCHAR(10),
  FOREIGN KEY (H_ID) REFERENCES HOSPITAL (H_ID),
  FOREIGN KEY (BRANCH_ID) REFERENCES BLOOD_BANK (Branch_ID) );
  

















  
  

